### ISSUE TITLE
Russian Translations

### ISSUE THREAD

**Issue by pjhampton** [elixirschool/elixirschool#220] opened 2016-03-25 13:58 UTC
## Get Involved!

We are seeking **Russian** translators for this project. If you would like to get involved with translating a lesson please fork the project and start translating.

- **Set up**
  - [x] _config.yml (@brain-geek)
  - [x] index.md (@brain-geek)
- **Basics**
  - [x] basics.md (@brain-geek)
  - [x] collections.md (@brain-geek)
  - [x] enum.md (@brain-geek)
  - [x] pattern-matching.md (@brain-geek)
  - [x] control-structures.md (@brain-geek)
  - [x] functions.md (@brain-geek)
  - [x] pipe-operator.md (@brain-geek)
  - [x] modules.md (@brain-geek)
  - [x] mix.md (@brain-geek)
  - [x] sigils.md (@nscyclone)
  - [x] documentation.md (@brain-geek)
  - [x] testing.md (@nscyclone)
  - [x] comprehensions.md (@nscyclone)
  - [x] strings.md (@nscyclone)
  - [x] mix-tasks.md (@nscyclone)
  - [ ] iex-helpers.md
- **Advanced**
  - [x] erlang.md (@brain-geek)
  - [x] error-handling.md (@nscyclone)
  - [x] escripts.md (@nscyclone)
  - [x] concurrency.md (@nscyclone)
  - [x] otp-concurrency.md (@brain-geek)
  - [x] otp-supervisors.md (@nscyclone)
  - [x] metaprogramming.md (@brain-geek)
  - [x] umbrella-projects.md (@yuriibodarev)
  - [x] typespecs.md (@yuriibodarev)
  - [x] behaviours.md (@yuriibodarev)
  - [x] gen-stage.md (@Saneery)
  - [x] protocols.md (@brain-geek)
- **Specifics**
  - [x] plug.md (@yuriibodarev)
  - [x] ecto.md (@tetiana12345678)
  - [x] eex.md (@yuriibodarev)
  - [x] ets.md (@brain-geek)
  - [x] mnesia.md (@nscyclone)
  - [ ] debugging.md
- **Libraries**
  - [x] guardian.md (@brain-geek)
  - [x] poolboy.md (@nscyclone)

**Note**
Those new to Elixir and / or Github are encouraged to get involved :smile:. 1 [Pull Request](https://help.github.com/articles/using-pull-requests/) per lesson.

**Comment by pjhampton** [comment] 2016-03-25 14:03
@brain-geek @tetiana12345678 & @gaynetdinov 

Let's close the other two (#218 + #99), and work within this one. If you are working on any lessons please let everyone know just incase someone is already working on it in this thread. Hope this is ok

:heart:

**Comment by brain-geek** [comment] 2016-03-26 10:23
I'll take "Functions" next. And "erlang.md" later on.

**Comment by tetiana12345678** [comment] 2016-03-27 13:24
great move.

**Comment by brain-geek** [comment] 2016-04-01 09:14
I'll take "Composition" next.

**Comment by nscyclone** [comment] 2016-04-03 08:43
I'm going to take `advanced/error-handling.md` next. It is called `errors.md` in this issue for some reason.

**Comment by brain-geek** [comment] 2016-04-03 09:05
I've marked it for you, @nscyclone .

**Comment by nscyclone** [comment] 2016-04-04 15:46
I'll start working on `advanced/concurrency.md` soon.

**Comment by nscyclone** [comment] 2016-04-22 18:03
`advanced/concurrency.md` is already merged (#266), so I guess we could mark it as translated here.
I'll take `basics/sigils.md` soon.

**Comment by brain-geek** [comment] 2016-04-24 20:48
I've updated the translations status. Also, I'll take otp-concurrency.md next.

**Comment by nscyclone** [comment] 2016-04-28 18:18
I'll take 'basics/comprehensions.md' next. It's original version is already merged but is not included in our list yet.

**Comment by brain-geek** [comment] 2016-05-01 11:15
I'll take "Documentation" next to finish up all 'Basics' lessons.

**Comment by nscyclone** [comment] 2016-05-23 05:08
I'm going to start translating the 'Mix Tasks' lesson soon.

**Comment by brain-geek** [comment] 2016-05-26 18:16
I'll take 'Metaprogramming' next.

**Comment by sobolevn** [comment] 2016-06-04 12:37
I'll take `eex`.

**Comment by doomspork** [comment] 2016-06-16 14:06
@brain-geek @nscyclone and everyone else, I'm wondering how best to track small changes to previously translated lessons and I was hoping to get your feedback.  Do you find this particular Issue format helpful?  Would it be sufficient to make additions to it for each change awaiting translation?  

I'm looking for ways to handle PRs like [#452](https://github.com/doomspork/elixir-school/pull/452), any thoughts would be greatly appreciated.

**Comment by nscyclone** [comment] 2016-06-16 15:38
@doomspork, I think this is the best option so far. The only question is how to automate this. Some sort of [webhook](https://developer.github.com/webhooks/) that would check whether a specific label is applied to an issue and then would apply the required changes to issues like this one when needed (adding an empty checkbox under the new `Improvements` section or something else).

**Comment by brain-geek** [comment] 2016-06-19 15:55
@nscyclone That's nice idea to create issues for each translation! 
We can do it manually - creating an issue ticket with checklist for each merged PR and look how it goes.

**Comment by brain-geek** [comment] 2016-06-22 17:50
I'm taking `ets.md` next.

**Comment by yuriibodarev** [comment] 2016-06-27 09:15
I can translate `eex.md` and after that I can take `plug.md`

**Comment by nscyclone** [comment] 2016-06-27 10:02
@yuriibodarev, AFAIK, `eex.md` is already a [WIP](https://github.com/doomspork/elixir-school/issues/220#issuecomment-223753441) by @sobolevn.

**Comment by sobolevn** [comment] 2016-06-27 10:03
we had a conversation, that it's totally fine by me.

**Comment by brain-geek** [comment] 2016-06-27 10:05
I've reassigned everything in first post according to Slack discussion.

**Comment by nscyclone** [comment] 2016-06-28 20:36
I've just updated the list because it lacked the `strings.md` lesson from the `basics` sections and the sections were described differently.
I'll try to find some time to send a PR with `strings.md` tonight.

**Comment by nscyclone** [comment] 2016-07-17 20:54
I've just started translating the last free lesson &mdash; `mnesia.md`.

**Comment by brain-geek** [comment] 2016-07-20 18:49
Wow, looks like we've translated all lessons to Russian!

Plug is still in review ( #542 ), but I guess we'll finish with it in a few days.

**Comment by brain-geek** [comment] 2016-07-20 18:51
Hm, not yet - there's new 'Umbrella projects' lesson. I'm adding it to top list.

**Comment by yuriibodarev** [comment] 2016-07-20 19:20
Can I take `Umbrella projects` for translation? I will start it after we'll finish with `Plug`!

**Comment by brain-geek** [comment] 2016-07-22 12:33
@yuriibodarev Sure, marked it as taken by you.

**Comment by nscyclone** [comment] 2016-08-24 19:21
There is a [new lesson](https://github.com/doomspork/elixir-school/blob/master/lessons/advanced/typespec.md) in the `advanced` section. Does anyone want to take it?

**Comment by yuriibodarev** [comment] 2016-08-24 20:23
I will take it

**Comment by yuriibodarev** [comment] 2016-11-04 10:26
I think You can mark **typespec** as translated. And there is a new lesson on **behaviours** in Advanced which I want to take for translation!

**Comment by brain-geek** [comment] 2016-11-04 10:31
@yuriibodarev thanks for the note. Added and marked for you.

**Comment by Saneery** [comment] 2016-11-10 11:27
Hi @brain-geek, i want to take for translation a new lesson **GenStage**

**Comment by brain-geek** [comment] 2016-11-10 11:50
@Saneery Marked for you. Thanks!

**Comment by brain-geek** [comment] 2016-11-28 22:24
I'll take the fresh *guardian* lesson.

**Comment by saneery** [comment] 2016-12-15 06:03
You can mark GenStage lesson as translated.

**Comment by brain-geek** [comment] 2016-12-15 08:22
Thanks for noting. Marked.

**Comment by nscyclone** [comment] 2016-12-15 20:25
I'll start working on `Poolboy` this weekend.

**Comment by nscyclone** [comment] 2017-03-19 21:04
I was reviewing the translations today. It seems like some of them need to be updated:
* `basics/enum`;
* `basics/modules`;
* `advanced/metaprogramming`;
* `specifics/plug`.

Does anyone want to take a stab at them?

**Comment by brain-geek** [comment] 2017-03-24 09:12
@nscyclone I guess we should restructure this document somehow. e.g. list only TODO items or just keep it up-to-date. Other option would be closing this issue. Any ideas?

**Comment by nscyclone** [comment] 2017-03-24 10:21
@brain-geek Actually I've recently updated the task list according to the current translations state. 
The problem is that it doesn't yet reflect the newly added versioning: the lessons are simply divided in two groups depending on whether there is _any_ translation for it even it's outdated. So I think that maybe adding a version next to every lesson and unchecking the outdated ones would be sufficient for now.
We really shouldn't overcomplicate this. And it also would be nice to ask the other translators' opinion on this topic.

**Closed** 2018-05-07 18:19 UTC
Labels: low hanging fruit, translation, your first pr
