### ISSUE TITLE
Create labels to organize issues by languages

### ISSUE THREAD

**Issue by eksperimental** [elixirschool/elixirschool#1113] opened 2017-06-14 03:03 UTC
There are already 83 issues, and I'm sure many are related to translations,
We should have a way to let contributors see at one glance all issues where this person can contribute.

I know it's a lot of labels, but we should have something like: 
`language:EN`

**Comment by doomspork** [comment] 2017-06-14 04:15
This sounds like a good idea to me.  Thoughts @gemantzu / @nscyclone and others?

**Comment by nscyclone** [comment] 2017-06-14 07:50
That's definitely a great idea but I'm afraid that the issue itself is a duplicate of #1032.

**Comment by gemantzu** [comment] 2017-06-15 11:15
It is indeed a duplicate of #1032. I believe though, that the solution I suggested will be doable in a not so hard way due to @eksperimental 's refactoring job ( #1112 ), at least I think so from a quick look I took on the pull request. I'm sorry, I've been bloated so much with work this year that I have not been able to commit as much time as I would want and solve this issue.

**Comment by doomspork** [comment] 2017-09-27 22:21
I'm not sure if it's helpful or not but I created individual teams for each language group: https://github.com/orgs/elixirschool/teams/translators/teams

I figured this would make at least tagging for review easier, don't believe it solves the sorting issue.

**Comment by doomspork** [comment] 2017-09-28 17:49
Closing this in favor of #1032

**Closed by doomspork** 2017-09-28 17:49 UTC
